CREATE TABLE Livros(
ID INT AUTO_INCREMENT PRIMARY KEY,
TITULO VARCHAR(100),
AUTOR VARCHAR(100),
GENERO VARCHAR(100),
EDITORA VARCHAR(100),
ANO_PUBLICADO INT
) ENGINE = INNODB;

CREATE TABLE Usuarios(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(100),
EMAIL VARCHAR(100),
TELEFONE INT,
TIPO_USUARIO VARCHAR(100)
) ENGINE = INNODB;

CREATE TABLE Autores(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(100)
) ENGINE = INNODB;

CREATE TABLE Genero_Livro(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(100)
) ENGINE = INNODB;

CREATE TABLE Editoras(
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(100)
) ENGINE = INNODB;

CREATE TABLE Emprestimos(
ID INT AUTO_INCREMENT PRIMARY KEY,
ID_USUARIO INT NOT NULL,
ID_LIVRO INT NOT NULL,
DATA_EMPRESTIMO DATE,
DATA_DEVOLUCAO DATE,
DEVOLVIDO BOOLEAN DEFAULT FALSE,

FOREIGN KEY (ID_USUARIO) REFERENCES Usuarios(ID),
FOREIGN KEY (ID_LIVRO) REFERENCES Livros(ID)
) ENGINE = INNODB;